# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tadd < Formula
  desc "Single binary, no dependency, utility to quickly create Todoist task."
  homepage "https://github.com/mchmarny/tadd"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/tadd/releases/download/v0.4.3/tadd_darwin_amd64"
      sha256 "1a79b61a786fd9d767c3f2cb70475b26a157ffdcbdb421703b450d625b2ee263"

      def install
        bin.install "tadd_darwin_amd64" => "tadd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/tadd/releases/download/v0.4.3/tadd_darwin_arm64"
      sha256 "460cfd1959af42503c3fe189898a3e3e75aa83b2dc962045f29abb0ecbecefd9"

      def install
        bin.install "tadd_darwin_arm64" => "tadd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/tadd/releases/download/v0.4.3/tadd_linux_arm64"
      sha256 "ba16f5881770dd47dfa993ab629c76beb3bd97bc3801b8f8684a639d3e044751"

      def install
        bin.install "tadd_linux_arm64" => "tadd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/tadd/releases/download/v0.4.3/tadd_linux_amd64"
      sha256 "478b63be5e408215585664d251193d2951561d170174a7a142987df0f7866a2c"

      def install
        bin.install "tadd_linux_amd64" => "tadd"
      end
    end
  end
end
